spring:
  datasource:
    url: jdbc:h2:mem:beruang
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE

springdoc:
  swagger-ui:
    path: /api
