spring:
  profiles:
    include:
      - dev

logging:
    file:
        name: logs/beruang-server
    pattern:
        console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%logger - %line]: %m%n"
        file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%logger - %line]: %m%n"
    level:
        root: INFO